# error codes
module LJ_FFI
  module Error
    SCRATCH_WRT_FAIL = 1
    SCRATCH_ERASE_FAIL = 2
    DATA_BUFFER_OVERFLOW = 3
    ADC0_BUFFER_OVERFLOW = 4
    FUNCTION_INVALID = 5
    SWDT_TIME_INVALID = 6
    XBR_CONFIG_ERROR = 7
    FLASH_WRITE_FAIL = 16
    FLASH_ERASE_FAIL = 17
    FLASH_JMP_FAIL = 18
    FLASH_PSP_TIMEOUT = 19
    FLASH_ABORT_RECEIVED = 20
    FLASH_PAGE_MISMATCH = 21
    FLASH_BLOCK_MISMATCH = 22
    FLASH_PAGE_NOT_IN_CODE_AREA = 23
    MEM_ILLEGAL_ADDRESS = 24
    FLASH_LOCKED = 25
    INVALID_BLOCK = 26
    FLASH_ILLEGAL_PAGE = 27
    FLASH_TOO_MANY_BYTES = 28
    FLASH_INVALID_STRING_NUM = 29
    SHT1x_COMM_TIME_OUT = 40
    SHT1x_NO_ACK = 41
    SHT1x_CRC_FAILED = 42
    SHT1X_TOO_MANY_W_BYTES = 43
    SHT1X_TOO_MANY_R_BYTES = 44
    SHT1X_INVALID_MODE = 45
    SHT1X_INVALID_LINE = 46
    STREAM_IS_ACTIVE = 48
    STREAM_TABLE_INVALID = 49
    STREAM_CONFIG_INVALID = 50
    STREAM_BAD_TRIGGER_SOURCE = 51
    STREAM_NOT_RUNNING = 52
    STREAM_INVALID_TRIGGER = 53
    STREAM_ADC0_BUFFER_OVERFLOW = 54
    STREAM_SCAN_OVERLAP = 55
    STREAM_SAMPLE_NUM_INVALID = 56
    STREAM_BIPOLAR_GAIN_INVALID = 57
    STREAM_SCAN_RATE_INVALID = 58
    STREAM_AUTORECOVER_ACTIVE = 59
    STREAM_AUTORECOVER_REPORT = 60
    STREAM_AUTORECOVER_OVERFLOW = 63
    TIMER_INVALID_MODE = 64
    TIMER_QUADRATURE_AB_ERROR = 65
    TIMER_QUAD_PULSE_SEQUENCE = 66
    TIMER_BAD_CLOCK_SOURCE = 67
    TIMER_STREAM_ACTIVE = 68
    TIMER_PWMSTOP_MODULE_ERROR = 69
    TIMER_SEQUENCE_ERROR = 70
    TIMER_LINE_SEQUENCE_ERROR = 71
    TIMER_SHARING_ERROR = 72
    EXT_OSC_NOT_STABLE = 80
    INVALID_POWER_SETTING = 81
    PLL_NOT_LOCKED = 82
    INVALID_PIN = 96
    PIN_CONFIGURED_FOR_ANALOG = 97
    PIN_CONFIGURED_FOR_DIGITAL = 98
    IOTYPE_SYNCH_ERROR = 99
    INVALID_OFFSET = 100
    IOTYPE_NOT_VALID = 101
    TC_PIN_OFFSET_MUST_BE_4_8 = 102
    UART_TIMEOUT = 112
    UART_NOT_CONNECTED = 113
    UART_NOT_ENABLED = 114
  end

  def error_string(code)
    sym = LJ_FFI::Error.constants.detect { |c| LJ_FFI::Error.const_get(c) == code }
    sym ||= 'unknown error'
    sym.to_s
  end
end
